var teamData = {
	NYJ: {
		division: 'AFC East',
		owner: 'Woody Johnson',
		primaryColor: 'Gotham Green',
		bestCurrentPlayer: 'Breece Hall (running back)',
		bestAllTimePlayer: 'Joe Namath (quarterback)',
		headCoach: 'Aaron Glenn',
		yearFounded: '1959',
		bestAllTimeRecord: '12-4 (1998)',
		powerRanking: '31st (3-14)'
	},
	BUF: {
		division: 'AFC East',
		owner: 'Terry Pegula',
		primaryColor: 'Royal Blue',
		bestCurrentPlayer: 'Josh Allen (quarterback)',
		bestAllTimePlayer: 'Bruce Smith (defensive end)',
		headCoach: 'Sean McDermott',
		yearFounded: '1960',
		bestAllTimeRecord: '13-3 (1990, 1991)',
		powerRanking: '7th (12-5)'
	},
	NE: {
		division: 'AFC East',
		owner: 'Robert Kraft',
		primaryColor: 'Nautical Blue',
		bestCurrentPlayer: 'Drake Maye (quarterback)',
		bestAllTimePlayer: 'Tom Brady (quarterback)',
		headCoach: 'Mike Vrabel',
		yearFounded: '1960',
		bestAllTimeRecord: '16-0 (2007)',
		powerRanking: '3rd (14-3)'
	},
	MIA: {
		division: 'AFC East',
		owner: 'Stephen M. Ross',
		primaryColor: 'Aqua',
		bestCurrentPlayer: 'Devon Achane (running back)',
		bestAllTimePlayer: 'Dan Marino (quarterback)',
		headCoach: 'Jeff Hafley',
		yearFounded: '1966',
		bestAllTimeRecord: '17-0 (1972)',
		powerRanking: '22nd (7-10)'
	},
	KC: {
		division: 'AFC West',
		owner: 'Clark Hunt',
		primaryColor: 'Red',
		bestCurrentPlayer: 'Patrick Mahomes (quarterback)',
		bestAllTimePlayer: 'Patrick Mahomes (quarterback)',
		headCoach: 'Andy Reid',
		yearFounded: '1960',
		bestAllTimeRecord: '14-2 (2018, 2019, 2020)',
		powerRanking: '24th (6-11)'
	},
	DEN: {
		division: 'AFC West',
		owner: 'The Walton-Penner Group',
		primaryColor: 'Orange',
		bestCurrentPlayer: 'Bo Nix (quarterback)',
		bestAllTimePlayer: 'John Elway (quarterback)',
		headCoach: 'Sean Payton',
		yearFounded: '1960',
		bestAllTimeRecord: '14-2 (1998)',
		powerRanking: '2nd (14-3)'
	},
	LAC: {
		division: 'AFC West',
		owner: 'Dean Spanos',
		primaryColor: 'Electric Blue',
		bestCurrentPlayer: 'Derwin James jr. (safety)',
		bestAllTimePlayer: 'Junior Seau (linebacker)',
		headCoach: 'Jim Harbaugh',
		yearFounded: '1960',
		bestAllTimeRecord: '14-2 (2006)',
		powerRanking: '11th (11-6)'
	},
	LV: {
		division: 'AFC West',
		owner: 'Mark Davis',
		primaryColor: 'Black',
		bestCurrentPlayer: 'Max Crosby (defensive end)',
		bestAllTimePlayer: 'Jim Otto (center)',
		headCoach: 'Klint Kubiak',
		yearFounded: '1960',
		bestAllTimeRecord: '13-3 (1974, 1976)',
		powerRanking: '30th (3-14)'
	},
	BAL: {
		
		division: 'AFC North',
		owner: 'Steve Bisciotti',
		primaryColor: 'Purple',
		bestCurrentPlayer: 'Lamar Jackson (quarterback)',
		bestAllTimePlayer: 'Ray Lewis (linebacker)',
		headCoach: 'Jesse Minter',
		yearFounded: '1996',
		bestAllTimeRecord: '14-2 (2019)',
		powerRanking: '20th (8-9)'
	},
	CIN: {
		division: 'AFC North',
		owner: 'Mike Brown',
		primaryColor: 'Orange',
		bestCurrentPlayer: 'Jamar Chase (wide receiver)',
		bestAllTimePlayer: 'Anthony Muñoz (offensive tackle)',
		headCoach: 'Zac Taylor',
		yearFounded: '1968',
		bestAllTimeRecord: '12-4 (1981, 1988, 2015)',
		powerRanking: '25th (6-11)'
	},
	PIT: {
		division: 'AFC North',
		owner: 'Art Rooney II',
		primaryColor: 'Gold',
		bestCurrentPlayer: 'T.J. Watt (linebacker)',
		bestAllTimePlayer: 'Joe Greene (defensive tackle)',
		headCoach: 'Mike McCarthy',
		yearFounded: '1933',
		bestAllTimeRecord: '15-1 (2004)',
		powerRanking: '12th (10-7)'
	}
	,
	CLE: {
		division: 'AFC North',
		owner: 'Jimmy and Dee Haslam',
		primaryColor: 'Brown',
		bestCurrentPlayer: 'Myles Garrett (defensive end)',
		bestAllTimePlayer: 'Myles Garrett (defensive end)',
		headCoach: 'Todd Monken',
		yearFounded: '1946',
		bestAllTimeRecord: '11-3 (1953)',
		powerRanking: '27th (5-12)'
	},
	HOU: {
		division: 'AFC South',
		owner: 'Janice and Cal McNair',
		primaryColor: 'Deep Steel Blue',
		bestCurrentPlayer: 'Derrick Stingley (safety)',
		bestAllTimePlayer: 'J.J. Watt (defensive end)',
		headCoach: 'DeMeco Ryans',
		yearFounded: '2002',
		bestAllTimeRecord: '12-4 (2012)',
		powerRanking: '8th (12-5)'
	},
	IND: {
		division: 'AFC South',
		owner: 'Jim Irsay',
		primaryColor: 'Speed Blue',
		bestCurrentPlayer: 'Jonathan Taylor (running back)',
		bestAllTimePlayer: 'Peyton Manning (quarterback)',
		headCoach: 'Shane Steichen',
		yearFounded: '1953',
		bestAllTimeRecord: '14-2 (2005, 2009)',
		powerRanking: '19th (8-9)'
	},
	JAX: {
		division: 'AFC South',
		owner: 'Shahid Khan',
		primaryColor: 'Teal',
		bestCurrentPlayer: 'Trevor Lawrence (quarterback)',
		bestAllTimePlayer: 'Tony Boselli (offensive tackle)',
		headCoach: 'Liam Coen',
		yearFounded: '1995',
		bestAllTimeRecord: '14-2 (1999)',
		powerRanking: '4th (13-4)'
	},
	TEN: {
		division: 'AFC South',
		owner: 'Amy Adams Strunk',
		primaryColor: 'Titans Blue',
		bestCurrentPlayer: 'Jeffery Simmons (defensive tackle)',
		bestAllTimePlayer: 'Bruce Matthews (offensive guard)',
		headCoach: 'Robert Saleh',
		yearFounded: '1960',
		bestAllTimeRecord: '13-3 (1993, 2000, 2008)',
		powerRanking: '32nd (3-14)'
	},
	CHI: {
		division: 'NFC North',
		owner: 'George McCaskey',
		primaryColor: 'Navy Blue',
		bestCurrentPlayer: 'Jaylon Johnson (Cornerback)',
		bestAllTimePlayer: 'Walter Payton (running back)',
		headCoach: 'Ben Johnson',
		yearFounded: '1920',
		bestAllTimeRecord: '15-1 (1985)',
		powerRanking: '10th (11-6)'
	},
	DET: {
		division: 'NFC North',
		owner: 'Sheila Ford Hamp',
		primaryColor: 'Honolulu Blue',
		bestCurrentPlayer: 'Penei Sewell (offensive tackle)',
		bestAllTimePlayer: 'Barry Sanders (running back)',
		headCoach: 'Dan Campbell',
		yearFounded: '1930',
		bestAllTimeRecord: '14-3 (2024)',
		powerRanking: '15th (9-8)'
	},
	GB: {
		division: 'NFC North',
		owner: 'Green Bay Packers, Inc.',
		primaryColor: 'Dark Green',
		bestCurrentPlayer: 'Xavier McKinney (safety)',
		bestAllTimePlayer: 'Aaron Rodgers (quarterback)',
		headCoach: 'Matt LaFleur',
		yearFounded: '1921',
		bestAllTimeRecord: '15-1 (2011)',
		powerRanking: '13th (9-7)'
	},
	MIN: {
		division: 'NFC North',
		owner: 'Zygi Wilf',
		primaryColor: 'Purple',
		bestCurrentPlayer: 'Justin Jefferson (wide receiver)',
		bestAllTimePlayer: 'Randy Moss (wide receiver)',
		headCoach: 'Kevin O\'Connell',
		yearFounded: '1961',
		bestAllTimeRecord: '15-1 (1998)',
		powerRanking: '14th (9-8)'
	},
	DAL: {
		division: 'NFC East',
		owner: 'Jerry Jones',
		primaryColor: 'Royal Blue',
		bestCurrentPlayer: 'CeeDee Lamb (wide receiver)',
		bestAllTimePlayer: 'Emmitt Smith (running back)',
		headCoach: 'Brian Schottenheimer',
		yearFounded: '1960',
		bestAllTimeRecord: '13-3 (1992)',
		powerRanking: '21st (7-9)'
	},
	NYG: {
		division: 'NFC East',
		owner: 'John Mara and Steve Tisch',
		primaryColor: 'Royal Blue',
		bestCurrentPlayer: 'Malik Naber (wide receiver)',
		bestAllTimePlayer: 'Lawrence Taylor (linebacker)',
		headCoach: 'John Harbaugh',
		yearFounded: '1925',
		bestAllTimeRecord: '14-2 (1986)',
		powerRanking: '28th (4-13)'
	},
	PHI: {
		division: 'NFC East',
		owner: 'Jeffery Lurie',
		primaryColor: 'Midnight Green',
		bestCurrentPlayer: 'Saqon Barkley (running back)',
		bestAllTimePlayer: 'Reggie White (defensive end)',
		headCoach: 'Nick Sirianni',
		yearFounded: '1933',
		bestAllTimeRecord: '14-3 (2022)',
		powerRanking: '9th (11-6)'
	},
	WAS: {
		division: 'NFC East',
		owner: 'Josh Harris',
		primaryColor: 'Burgundy',
		bestCurrentPlayer: 'Jayden Daniels (quarterback)',
		bestAllTimePlayer: 'Sammy Baugh (quarterback)',
		headCoach: 'Dan Quinn',
		yearFounded: '1932',
		bestAllTimeRecord: '14-2 (1991)',
		powerRanking: '26th (5-12)'
	},
	ATL: {
		division: 'NFC South',
		owner: 'Arthur Blank',
		primaryColor: 'Red',
		bestCurrentPlayer: 'Bijan Robinson (running back)',
		bestAllTimePlayer: 'Julio Jones (wide receiver)',
		headCoach: 'Kevin Stefanski',
		yearFounded: '1966',
		bestAllTimeRecord: '14-2 (1998)',
		powerRanking: '18th (8-9)'
	},
	CAR: {
		division: 'NFC South',
		owner: 'David Tepper',
		primaryColor: 'Carolina Blue',
		bestCurrentPlayer: 'Derrick Brown (defensive tackle)',
		bestAllTimePlayer: 'Steve Smith Sr. (wide receiver)',
		headCoach: 'Dave Canales',
		yearFounded: '1995',
		bestAllTimeRecord: '15-1 (2015)',
		powerRanking: '16th (8-9)'
	},
	NO: {
		division: 'NFC South',
		owner: 'Gayle Benson',
		primaryColor: 'Black',
		bestCurrentPlayer: 'Chris Olave (wide receiver)',
		bestAllTimePlayer: 'Drew Brees (quarterback)',
		headCoach: 'Kellen Moore',
		yearFounded: '1967',
		bestAllTimeRecord: '13-3 (2019)',
		powerRanking: '23rd (6-11)'
	},
	TB: {
		division: 'NFC South',
		owner: 'Bryan Glazer',
		primaryColor: 'Red',
		bestCurrentPlayer: 'Antoine Winfield Jr. (safety)',
		bestAllTimePlayer: 'Derrick Brooks (linebacker)',
		headCoach: 'Todd Bowles',
		yearFounded: '1976',
		bestAllTimeRecord: '13-4 (2021)',
		powerRanking: '17th (8-9)'
	},
	ARI: {
		division: 'NFC West',
		owner: 'Michael Bidwill',
		primaryColor: 'Cardinal Red',
		bestCurrentPlayer: 'Trey McBride (tight end)',
		bestAllTimePlayer: 'Larry Fitzgerald (wide receiver)',
		headCoach: 'Mike Lafleur',
		yearFounded: '1920',
		bestAllTimeRecord: '13-3 (2015)',
		powerRanking: '29th (3-14)'
	},
	LAR: {
		division: 'NFC West',
		owner: 'Stan Kroenke',
		primaryColor: 'Royal Blue',
		bestCurrentPlayer: 'Puka Nacua (wide receiver)',
		bestAllTimePlayer: 'Aaron Donald (defensive tackle)',
		headCoach: 'Sean McVay',
		yearFounded: '1937',
		bestAllTimeRecord: '14-2 (2001)',
		powerRanking: '5th (12-5)'
	},
	SF: {
		division: 'NFC West',
		owner: 'Jed York',
		primaryColor: 'Scarlet Red',
		bestCurrentPlayer: 'Christain McCaffrey (running back)',
		bestAllTimePlayer: 'Jerry Rice (wide receiver)',
		headCoach: 'Kyle Shanahan',
		yearFounded: '1946',
		bestAllTimeRecord: '15-1 (1984',
		powerRanking: '6th (12-5)'
	},
	SEA: {
		division: 'NFC West',
		owner: 'Jody Allen',
		primaryColor: 'College Navy',
		bestCurrentPlayer: 'Jaxon Smith-Njigba (wide receiver)',
		bestAllTimePlayer: 'Russell Wilson (quarterback)',
		headCoach: 'Mike MacDonald',
		yearFounded: '1976',
		bestAllTimeRecord: '13-3 (2005 & 2013)',
		powerRanking: '1st (14-3)'
 	}
};
