var stateData = {
	NYJ: {
		division: 'AFC East',
		owner: 'Woody Johnson',
		primaryColor: 'Green',
		bestCurrentPlayer: 'Breece Hall',
		bestAllTimePlayer: 'Darelle Revis',
		headCoach: 'Aaron Glenn',
		yearFounded: '1959',
		bestAllTimeRecord: '11-3 (1968)',
		powerRanking: '31st (3-14)'
	},
	BUF: {
		division: 'AFC East',
		owner: 'Terry Pegula',
		primaryColor: 'Blue',
		bestCurrentPlayer: 'Josh Allen',
		bestAllTimePlayer: 'Bruce Smith',
		headCoach: 'Sean McDermott',
		yearFounded: '1960',
		bestAllTimeRecord: '',
		powerRanking: '7th (12-5)'
	},
	NE: {
		division: 'AFC East',
		owner: 'Robert Kraft',
		primaryColor: '',
		bestCurrentPlayer: 'Drake Maye',
		bestAllTimePlayer: 'Tom Brady',
		headCoach: 'Mike Vrabel',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '3rd (14-3)'
	},
	MIA: {
		division: 'AFC East',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: 'Devon Achane',
		bestAllTimePlayer: 'Dan Marino',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '22nd (7-10)'
	},
	KC: {
		division: 'AFC West',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: 'Patrick Mahomes',
		bestAllTimePlayer: 'Patrick Mahomes',
		headCoach: 'Andy Reid',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '24th (6-11)'
	},
	DEN: {
		division: 'AFC West',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: 'Bo Nix',
		bestAllTimePlayer: 'Peyton Manning',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '2nd (14-3)'
	},
	LAC: {
		division: 'AFC West',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: 'Derwin James jr.',
		bestAllTimePlayer: 'LaDainian Tomlinson',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '11th (11-6)'
	},
	LV: {
		division: 'AFC West',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: 'Max Crosby',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '30th (3-14'
	},
	BAL: {
		division: 'AFC North',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: 'Lamar Jackson',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '20th (8-9)'
	},
	CIN: {
		division: 'AFC North',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: 'Jamar Chase',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '25th (6-11)'
	}
	PIT: {
		division: 'AFC North',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: 'T.J. Watt',
		bestAllTimePlayer: 'Antonio Brown',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '12th (10-7)'
	}
	CLE: {
		division: 'AFC North',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: 'Myles Garrett',
		bestAllTimePlayer: 'Myles Garrett',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '27th (5-12)'
	},
	HOU: {
		division: 'AFC South',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: 'Derrick Stingley',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '8th (12-5)'
	},
	IND: {
		division: 'AFC South',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '19th (8-9)'
	},
	JAX: {
		division: 'AFC South',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '4th (13-4)'
	},
	TEN: {
		division: 'AFC South',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '32nd (3-14)'
	},
	CHI: {
		division: 'NFC North',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '0th (11-6)'
	},
	DET: {
		division: 'NFC North',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '15th (9-8)'
	},
	GB: {
		division: 'NFC North',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '13th (9-7)'
	},
	MV: {
		division: 'NFC North',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '14th (9-8)'
	},
	DAL: {
		division: 'NFC East',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '21st (7-9)'
	},
	NYG: {
		division: 'NFC East',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '28th (4-13)'
	},
	PHI: {
		division: 'NFC East',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '9th (11-6)'
	},
	WAS: {
		division: 'NFC East',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '26th (5-12)'
	},
	ATL: {
		division: 'NFC South',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '18th (8-9)'
	},
	CAR: {
		division: 'NFC South',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '16th (8-9)'
	},
	NO: {
		division: 'NFC South',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '23rd (6-11)'
	},
	TB: {
		division: 'NFC South',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '17th (8-9)'
	},
	ARI: {
		division: 'NFC West',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '29th (3-14)'
	},
	LAR: {
		division: 'NFC West',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '5th (12-5)'
	},
	SF: {
		division: 'NFC West',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '6th (12-5)'
	},
	SEA: {
		division: 'NFC West',
		owner: '',
		primaryColor: '',
		bestCurrentPlayer: '',
		bestAllTimePlayer: '',
		headCoach: '',
		yearFounded: '',
		bestAllTimeRecord: '',
		powerRanking: '1st (14-3)'
	},
